import { Command, Input } from '@api';

export class Pun extends Command {
    constructor() {
        super({
            name: 'pun',
            description: 'Displays a random pun.'
        });
    }

    //TODO: Allow users/admins to enter custom puns

    execute(input: Input) {
            let puns = [
                "About a month before he died, my uncle had his back covered in lard. After that, he went down hill fast.",
                "The first computer dates back to Adam and Eve. It was an Apple with limited memory, just one byte. And then everything crashed.",
                "I bought some shoes from a drug dealer. I don't know what he laced them with, but I've been tripping all day.",
                "\"Doctor, there's a patient on line 1 that says he's invisible.\" \"Well, tell him I can't see him right now.\" ",
                "Thanks for explaining the word \"many\" to me, it means a lot.",
                "My dad died when we couldn't remember his blood type. As he died, he kept insisting for us to \"be positive,\" but it's hard without him.",
                "My girlfriend told me she was leaving me because I keep pretending to be a Transformer. I said, \"No, wait! I can change.\"",
                "R.I.P boiled water. You will be mist.",
                "The future, the present and the past walked into a bar. Things got a little tense.",
                "eBay is so useless. I tried to look up lighters and all they had was 13,749 matches.",
                "Atheism is a non-prophet organization.",
                "I saw an ad for burial plots, and thought to myself this is the last thing I need.",
                "I just found out I'm colorblind. The diagnosis came completely out of the purple.",
                "What's the difference of deer nuts and beer nuts? Beer nuts are a $1.75, but deer nut are under a buck.",
                "Just burned 2,000 calories. That's the last time I leave brownies in the oven while I nap.",
                "I was addicted to the hokey pokey... but thankfully, I turned myself around.",
                "Claustrophobic people are more productive thinking out of the box.",
                "Don't trust atoms, they make up everything.",
                "Atheists don't solve exponential equations because they don't believe in higher powers.",
                "What do you call a dictionary on drugs? HIGH-Definition.",
                "To the mathematicians who thought of the idea of zero, thanks for nothing!",
                "I got a new pair of gloves today, but they're both 'lefts' which, on the one hand, is great, but on the other, it's just not right.",
                "A cop just knocked on my door and told me that my dogs were chasing people on bikes. My dogs don't even own bikes...",
                "What do you call the security outside of a Samsung Store? Guardians of the Galaxy.",
                "What did E.T.'s mother say to him when he got home? \"Where on Earth have you been?!\"",
                "A mexican magician was doing a magic trick. He said, Uno, Dose, and he disappeared without a trace",
                "What's the difference between a poorly dressed man on a bicycle and a nicely dressed man on a tricycle? A tire.",
                "I can't believe I got fired from the calendar factory. All I did was take a day off.",
                "I'm reading a book about anti-gravity. It's impossible to put down.",
                "I wasn't originally going to get a brain transplant, but then I changed my mind.",
                "Did you hear about the kidnapping at school? It's okay. He woke up.",
                "I ordered 2000 lbs. of chinese soup. It was Won Ton.",
                "Don't spell part backwards. It's a trap.",
                "Did you hear about the guy who got hit in the head with a can of soda? He was lucky it was a soft drink.",
                "A courtroom artist was arrested today for an unknown reason... details are sketchy.",
                "Oxygen is proven to be a toxic gas. Anyone who inhales oxygen will normally die within 80 years.",
                "A termite walks into a bar and says, \"Where is the bar tender?\"",
                "I accidentally handed my wife a glue stick instead of a chapstick. She still isn't talking to me.",
                "Why was Cinderella thrown off the basketball team? She ran away from the ball.",
                "How did I escape Iraq? Iran.",
                "I'd tell you a chemistry joke but I know I wouldn't get a reaction.",
                "I used to be addicted to soap, but I'm clean now.",
                "What do you call a priest that becomes a lawyer? A father in law.",
                "I don't engage in mental combat with the unarmed.",
                "I've just written a song about tortillas - actually, it's more of a rap.",
                "Heard about the drug addict fisherman who accidentally caught a duck? Now he's hooked on the quack.",
                "If a short psychic broke out of jail, then you'd have a small medium at large.",
                "Dr.'s are saying not to worry about the bird flu because it's tweetable.",
                "Got my girlfriend a \"get better soon\" card. She's not sick, I just think she could get better.",
                "What is the best thing about living in Switzerland? Well, the flag is a big plus.",
                "If 4 out of 5 people SUFFER from diarrhea... does that mean that one enjoys it?",
                "For Halloween we dressed up as almonds. Everyone could tell we were nuts.",
                "I have a few jokes about unemployed people but it doesn't matter none of them work.",
                "Two blondes were driving to Disneyland. The sign said, \"Disneyland Left\". So they started crying and went home.",
                "I'm glad I know sign language, it's pretty handy.",
                "Did you hear about the man who jumped off a bridge in France? He was in Sein.",
                "Thieves had broken into my house and stolen everything except my soap, shower gel, towels and deodorant. Dirty Bastards.",
                "What do you call a laughing motorcycle? A Yamahahaha.",
                "I found a rock yesterday which measured 1760 yards in length. Must be some kind of milestone.",
                "I'm emotionally constipated. I haven't given a shit in days.",
                "Did you hear they banned fans from doing \"The Wave\" at all sports events? Too many blondes were drowning",
                "My girlfriend said, \"You act like a detective too much. I want to split up.\" \"Good idea,\" I replied. \"We can cover more ground that way.\"",
                "My wife likes it when I blow air on her when she's hot, but honestly... I'm not a fan.",
                "This morning some clown opened the door for me. I thought to myself that's a nice Jester.",
                "Police have arrested the World tongue-twister Champion. I imagine he'll be given a tough sentence.",
                "I've decided to sell my Hoover... well, it was just collecting dust.",
                "If a child refuses to sleep during nap time, are they guilty of resisting a rest?",
                "Why don't aliens visit our planet? Terrible ratings. One star.",
                "Why do the French eat snails? They don't like fast food.",
                "My doctors office has two doctors on call at all times. Is that considered a pair a docs.",
                "A friend of mine tried to annoy me with bird puns, but I soon realized that toucan play at that game.",
                "Did you hear about these new reversible jackets? I'm excited to see how they turn out.",
                "When I get naked in the bathroom, the shower usually gets turned on.",
                "Why do seagulls fly over the sea? Because if they flew over the bay they'd be bagels!",
                "My first job was working in an orange juice factory, but I got canned: couldn't concentrate.",
                "Why couldn't the bike stand up on it's own? It was two tired.",
                "I hate peer pressure and you should too.",
                "A book just fell on my head. I've only got myshelf to blame.",
                "My boss says I intimidate the other employees, so I just stared at him until he apologized.",
                "Why did the scientist install a knocker on his door? He wanted to win the No-bell prize!",
                "My math teacher called me average. How mean!",
                "How did Jesus' crucifixion save us? It's 'cause he nailed it!",
                "What do you have to do to have a party in space? You have to Planet.",
                "Why couldn't the leopard play hide and seek? Because he was always spotted.",
                "Why did the cross-eyed teacher lose her job? Because she couldn't control her pupils.",
                "Justice is a dish best served cold because if it were served warm, it would be justwater.",
                "What did one eye say to the other eye? Between you and me something smells.",
                "I'm no photographer, but I can picture us together.",
                "A teacher asks a student, \"Are you ignorant or just apathetic?\" The kid answers, \"I don't know and I don't care.\"",
                "I am on a seafood diet. Every time I see food, I eat it.",
                "I recently got a new Korean mechanic but it's hard to understand him - he speaks with a Hyundai Accent!",
                "To write with a broken pencil is pointless.",
                "What was Forrest Gump's email password? \"1forrest1\"",
                "What do you call a cow with no legs? Ground beef.",
                "Most people are shocked when they find out how bad I am as an electrician",
                "I bought a box of condoms earlier today. The cashier asked if I'd like a bag. I said \"nah, I'll just turn the lights off.\"",
                "What do you call a cow during an earthquake? A milkshake.",
                "Someone stole my toilet and the police have nothing to go on.",
                "My psychiatrist said I was pre-occupied with the vengeance I told him \"oh yeah we'll see about that!\"",
                "My boss is going to fire the employee with the worst posture. I have a hunch, it might be me.",
                "I used to be a banker, but then I lost interest.",
                "My computer's got Miley Virus. It has stopped twerking.",
                "I was born to be a pessimist. My blood type is B Negative.",
                "Last time I got caught stealing a calendar I got 12 months.",
                "I finally realized my parents favored my twin brother. It hit me when they asked me to blow up balloons for his surprise birthday party.",
                "I threw an Asian man down a flight of stairs. It was Wong on so many levels.",
                "The doctor told his patient to stop using a Q-tip, but it went in one ear and out the other.",
                "My boss told me to have a good day. So I went home.",
                "I relish the fact that you've mustard the strength to ketchup to me.",
                "I'm changing my name to 'Benefits' on Facebook. Next time someone adds me, It will say \"you are now friends with Benefits.\"",
                "What do you call a cow with a twitch? \"Beef Jerky!\"",
                "My grandfather tried to warn them about the Titanic. He screamed and shouted about the iceberg and how the ship was going to sink, but all they did was throw him out of the theater.",
                "Did you hear about the Italian chef with a terminal illness? He pastaway.",
                "I had a job tying sausages together, but I couldn't make ends meet.",
                "I wanna make a joke about sodium, but Na..",
                "I bought a dictionary and when I got home I realized all the pages were blank; I have no words for how angry I am.",
                "People don't get my puns. They think they're funny.",
                "A bus station is where a bus stops. A train station is where a train stops. On my desk, I have a work station..",
                "I ran out of poker chips so used dry fruits for playing instead. People went nuts when they saw me raisin the stakes.",
                "Having sex in an elevator is wrong on so many levels.",
                "What do prisoners use to call each other? Cell phones.",
                "Why did the bee get married? Because he found his honey.",
                "It's been raining for 3 days without stopping. My wife is in depression, she is standing and looking through the window. If the rain doesn't stop tomorrow, I'll have to let her in.",
                "Did you hear about the math teacher who's afraid of negative numbers? He will stop at nothing to avoid them.",
                "I had a neck brace fitted years ago and I've never looked back since.",
                "I'm trying to date a philosophy professor, but she doesn't even know if I exist or not.",
                "What do you call people who are afraid of Santa Claus? Claustrophobic",
                "I always wanted to marry an Archaeologist. The older I would get, the more interested she would become!",
                "I couldn't quite remember how to throw a boomerang, but eventually, it came back to me.",
                "When I was young, I always felt like a male trapped in a females body. Then I was born",
                "Are you Finnish? 'Cause I'd like to Finnish you off.",
                "With great reflexes comes great response ability.",
                "Confucius say, man who runs behind car will get exhausted, but man who runs in front of car will get tired.",
                "Did you hear about the 2 silk worms in a race? It ended in a tie!",
                "I hate insects puns, they really bug me.",
                "How can you spot the blind guy at the nudist colony? It's not hard.",
                "As a wizard, I enjoy turning objects into a glass. Just wanted to make that clear.",
                "What is the name of an Asian pilot who died in a plane crash? Sum Ting Wong.",
                "The nurse at the sperm bank asked me if I'd like to masturbate in the cup. I said, \"Well, I'm pretty good, but I don't think I'm ready to compete just yet.\"",
                "Why did the picture end up in jail? It was framed!",
                "I was going to give him a nasty look, but he already had one.",
                "I tried to escape the Apple store. I couldn't because there were no Windows.",
                "A hole was found in the wall of a nudist camp. The police are looking into it.",
                "It's hard to explain puns to kleptomaniacs because they always take things literally.",
                "What did one ocean say to the other ocean? Nothing, they just waved.",
                "I'm reading a horror story in Braille. Something bad is about to happen... I can feel it.",
                "What underwear does clouds wear? Thunderwear!",
                "How does Moses make his tea? Hebrews it.",
                "How does a snowman get around? He rides an icicle!",
                "What do sea monsters eat for lunch? Fish and ships.",
                "Cleaning mirrors is a job I could really see myself doing.",
                "I am so poor I can't even pay attention.",
                "The best time to open a gift is the present.",
                "You can't get on the same page with someone who has a different book.",
                "What is a baptized Mexican called? Bean dip.",
                "How do trees access the internet? They log in.",
                "I own a pencil that used to be owned by William Shakespeare, but he chewed it a lot. Now I can't tell if it's 2B or not 2B.",
                "I used to work at a fire hydrant factory couldn't park nowhere near the place.",
                "Do German cats have multiple lives? Nein.",
                "Why did Martin Luther King Jr. boycott laundry detergent? Because it told him to keep his whites and colors separate.",
                "My girlfriend tried to make me have sex on the hood of her Honda Civic. I refused. If I'm going to have sex, it's going to be on my own Accord.",
                "Three conspiracy theorists walk into a bar. You can't tell me that's just a coincidence!",
                "Tried watching The Neverending Story, couldn't finish it.",
                "My IQ test results just came in and I'm really relieved. Thank God it's negative.",
                "What do you call an academically successful slice of bread? An honor roll.",
                "Fishermen are reel men.",
                "What happens if you eat yeast and shoe polish? Every morning you will rise and shine!",
                "What do you call Watson when Sherlock isn't around? Holmeless.",
                "Anyone who wanted to sell fish had to get permission from grandpa. He was known as the cod father.",
                "Why do Swedish warships have barcodes on them? So when they dock they can Scandinavian.",
                "Isn't it scary that doctors call what they do \"practice\"?",
                "No matter how much you push the envelope, it'll still be stationery.",
                "Today, my son asked \"Can I have a book mark?\" and I burst into tears. 11 years old and he still doesn't know my name is Brian.",
                "For Sale: Parachute. Only used once, never opened.",
                "A garage sale is actually a Garbage sale but the \"b\" is silent.",
                "What happened when the semicolon broke grammar laws? It was given two consecutive sentences.",
                "I just found an origami porn channel, but it is paper view only.",
                "I'm taking part in a stair climbing competition. Guess I better step up my game.",
                "I put the \"fun\" in dysfunctional. ",
                "I worked in the woods as a lumberjack, but I just couldn't hack it, so they gave me the ax.",
                "When is a door not a door? When it's ajar.",
                "If the right side of the brain controls the left side of the body, then lefties are the only ones in their right mind.",
                "I tried to catch some fog, I mist.",
                "My buddy set me up on a blind date &amp; said, \"Heads up, she's expecting a baby.\" Felt like an idiot sitting in the bar wearing just a diaper.",
                "I wear two pairs of pants when I go golfing. People always ask me why I do. I say, \"I wear two pants when's I golf just in case I get a hole-in-one.",
                "If anything is possible, is it possible for something to be impossible?",
                "The first time I got a universal remote control, I thought to myself \"This changes everything\".",
                "Your gene pool could use a little chlorine.",
                "Why doesn't the bike stand by itself? Because it's two tired.",
                "What do ghosts serve for dessert? I Scream.",
                "Scientist: \"My findings are meaningless if taken out of context.\" Media: Scientist claims \"Findings are meaningless.\"",
                "I used to wonder why Frisbees looked bigger the closer it came... Then it hit me!",
                "What do you get when you cross a snowman and a vampire? Frost bite.",
                "What does \"reading comprehension\" even mean?",
                "My landlord says he needs to come talk to me about how high my heating bill is. I told him, \"My door is always open\".",
                "I got a part in a movie called \"Cocaine\". I only have one line.",
                "Two windmills are standing in a field and one asks the other, \"What kind of music do you like?\" The other says, \"I'm a big metal fan.\"",
                "Can a kangaroo jump higher than the Empire State Building? Of course. The Empire State Building can't jump.",
                "Did you hear about the depressed plumber? He's been going through some shit.",
                "What if there were no hypothetical questions?",
                "Grandma's been staring through the window ever since it started to snow. If it gets any worse I'll have to let her in.",
                "A guy goes to a club; the bouncer stops him. \"No tie, no entry.\" He walks back to his car to find a tie. All he found were jumper cables so he puts them around his neck like a tie. He goes back and says \"How's this?\" The bouncer says \"I'll let you in, but don't start anything.\"",
                "On the other hand, you have different fingers.",
                "Why was the tree excited about the future? It was ready to turn over a new leaf!",
                "How do you make a fire with two sticks? Make sure one of them is a match!",
                "My tennis opponent was not happy with my serve. He kept returning it.",
                "Hung a picture up on the wall the other day. Nailed it.",
                "Maybe it's not global warming. Maybe it's just planetary menopause.",
                "Someone broke into my house last night and stole my Limbo stick. How low can you get?",
                "What happens to the man who lost his whole left side of his body? He is all right now.",
                "Why don't cannibals eat clowns? They taste funny.",
                "I would give my right arm to be ambidextrous!",
                "If you believe that the quickest way to a man's heart is the stomach, you know that you are aiming a little too high.",
                "Tea is like F5 to me, it's refreshing.",
                "Teachers who take class attendance are absent-minded.",
                "Every time I tell a funny cow joke, I butcher it.",
                "Golfer: \"I'd move heaven and earth to break 100 on this course.\" Caddy: \"Try heaven; you've already moved most of the earth.\"",
                "What do people wear in a trench? Trench coats.",
                "I cooked Pancakes this morning. I was thrilled but my kids weren't. Apparently, he was their favorite rabbit.",
                "The artist thought his favourite paint had been stolen, but it was just a pigment of his imagination.",
                "Where does the Easter Bunny go to eat pancakes? To IHOP, of course!",
                //https://onelinefun.com/puns/22/
            ];
    
            let rnd = Math.floor(Math.random() * puns.length);

            input.channel.send({
                embed:
                {
                    color: 3447003,
                    title: `**Pun [${1 + rnd}]**`,
                    description:`${puns[rnd]}`
                }
            });

    }
}
